### ISSUE TITLE
你好作者，请问代码是完整的吗

### ISSUE THREAD

**Issue by tillmorning** [lgdlkq/sliver_07_CT#1]
作者想请问一下，代码是完整的吗

**Comment by lgdlkq** [comment]
没记错的话，可视化是个半成品，其他的部分是完整的，最开始的可视化想写exe，后来改成了web，这个里面没有包含web的代码

**Comment by tillmorning** [comment]
> 没记错的话，可视化是个半成品，其他的部分是完整的，最开始的可视化想写exe，后来改成了web，这个里面没有包含web的代码
作者有完整的作品地址吗

**Comment by tillmorning** [comment]
> 没记错的话，可视化是个半成品，其他的部分是完整的，最开始的可视化想写exe，后来改成了web，这个里面没有包含web的代码

或者作者有什么学习资料推荐一下吗？孩子只是个小白

**Comment by lgdlkq** [comment]
web端写的比较简陋，就不发出来了，你可以自己写一下

**Comment by lgdlkq** [comment]
> > 没记错的话，可视化是个半成品，其他的部分是完整的，最开始的可视化想写exe，后来改成了web，这个里面没有包含web的代码
> 
> 或者作者有什么学习资料推荐一下吗？孩子只是个小白

建议你先去看下相关的经典论文，比如Unet什么的，再看看最近几年的最新论文，可以结合着代码看看，根据你自己的实际需求去调整，有条件的话可以复现一下，自己看看效果

**Comment by tillmorning** [comment]
> > > 没记错的话，可视化是个半成品，其他的部分是完整的，最开始的可视化想写exe，后来改成了web，这个里面没有包含web的代码
> > 
> > 
> > 或者作者有什么学习资料推荐一下吗？孩子只是个小白
> 
> 建议你先去看下相关的经典论文，比如Unet什么的，再看看最近几年的最新论文，可以结合着代码看看，根据你自己的实际需求去调整，有条件的话可以复现一下，自己看看效果

好的，谢谢你
