### ISSUE TITLE
你好作者，想问一下整个项目代码的执行流程是怎样的

### ISSUE THREAD

**Issue by Rsdw1** [lgdlkq/sliver_07_CT#2]
data_slit.py文件好像只生成了三个.txt文件（就是neg开头的三个），然后就是reconstruction部分代码是不是缺少了一部分。小白求教
还有就是checkpoint里的文件是训练好的模型吗？好像损坏了，如果我用自己的数据去训练，应该怎么做呢？你这个训练好的模型是在哪一个文件中生成保存的呢？小白求教

**Comment by lgdlkq** [comment]
1.数据集划分确实只有三个文件生成的，github里面显示的是当时生成了三次的结果。2.reconstruction部分只写了简单的演示，并没完全写完，后面全改成web的了。3.checkpoint是训练好的模型。4.你需要根据自己的数据的进行相应的预处理，按照你自己的数据格式等编写Dataset类。5.训练、测试等入口在operation.py里面执行，保存模型函数在utils包下的utils.py中save_checkpoint函数实现。
